/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.question2;

import javax.swing.*;


/**
 *
 * @author tiger
 */
public class Invest extends javax.swing.JPanel {

    /**
     * Creates new form Invest
     */
    public Invest() {
        initComponents();
    }
   
    public static void main(String[] args) {
        //create investment frame and show frame
        JFrame frame = new JFrame("Invest");
        
        frame.setContentPane(new Invest());
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        menuBar = new javax.swing.JMenuBar();
        menuFiles = new javax.swing.JMenu();
        menuTools = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        txtCustName = new javax.swing.JTextField();
        txtAmount = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        term_5 = new javax.swing.JRadioButton();
        term_10 = new javax.swing.JRadioButton();
        rBtn15 = new javax.swing.JRadioButton();
        btnCalc = new javax.swing.JButton();

        menuFiles.setText("File");
        menuFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuFilesActionPerformed(evt);
            }
        });
        menuBar.add(menuFiles);

        menuTools.setText("Tools");
        menuTools.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuToolsActionPerformed(evt);
            }
        });
        menuBar.add(menuTools);

        jLabel1.setText("Customer Name:");

        txtCustName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustNameActionPerformed(evt);
            }
        });

        txtAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAmountActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter Amount:");

        jLabel3.setText("Select Type:");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moderate", "Aggressive" }));

        jLabel4.setText("Select Term:");

        buttonGroup1.add(term_5);
        term_5.setText("5 Years");

        buttonGroup1.add(term_10);
        term_10.setText("10 Years");

        buttonGroup1.add(rBtn15);
        rBtn15.setText("15 Years");

        btnCalc.setText("Calculate");
        btnCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCalc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rBtn15)
                            .addComponent(term_10)
                            .addComponent(term_5)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(txtCustName)
                                .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCustName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(term_5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(term_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rBtn15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(btnCalc)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCustNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustNameActionPerformed

    private void txtAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAmountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAmountActionPerformed

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcActionPerformed

        calculate();
    }//GEN-LAST:event_btnCalcActionPerformed

    private void menuFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuFilesActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuFilesActionPerformed

    private void menuToolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuToolsActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_menuToolsActionPerformed

    // Getter Methods
    // Getting Customer Name:
    public String getCustomerName() {
        return txtCustName.getText();
    }
    
    // Getting Amount
    public String getAmount() {
        return txtAmount.getText();
    }
    
    // Getting Type
    public String getType() {
        return cmbType.getSelectedItem().toString().trim();
    }
    // Getting Term
    public int getTerm() {
        if(term_5.isSelected()) {
            return 5;
        } else if(term_10.isSelected()) {
            return 10;
        } else {
            return 15;
        }
    }
    
    
    // Setter Methods
    //Setting CustomerName
    public void setCustomerName(String s){
        txtCustName.setText(s);
    }
    
    //Setting Amount
    public void setAmount(String s){
        txtAmount.setText(s);
    }
    
    // Setting Type
    public void setType(int i){
       cmbType.setSelectedIndex(i);
    }
    
    
    private void calculate() {
        
        //get amount from customer name text field
        double amount = Double.parseDouble(getAmount());
        //get intrest rate from type
        double interest = 0.10;
        String type = getType();
        if(type.equals("Moderate")) {
            interest = 0.10;
        } else if(type.equals("Aggressive")){
            interest = 0.15;
        }
        
        
        //get investment years
        int years = getTerm();
        
        double investment = amount * Math.pow(1 +(interest/12), 12*years);
        
        double compound_interest = investment - amount;
        
         String str = "INVESTMENT REPORT\n"
                + "\nCUSTOMER NAME: " + getCustomerName()
                + "\nORIGINAL AMOUNT: R" + getAmount()
                + "\nYEARS Invested: " + years
                + "\nFINAL AMOUNT: R " + String.format("%.2f",investment);
      
        //show message box with all the details
        JOptionPane.showMessageDialog(null, str);
        
    }
    
    //clear all text fields
    private void clear(){
        setCustomerName("");
        setAmount("");
        setType(0);
    }
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalc;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFiles;
    private javax.swing.JMenu menuTools;
    private javax.swing.JRadioButton rBtn15;
    private javax.swing.JRadioButton term_10;
    private javax.swing.JRadioButton term_5;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtCustName;
    // End of variables declaration//GEN-END:variables
}
