/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package carthingy;

import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;  // Import the IOException class to handle errors
import java.io.ObjectOutputStream;
import javax.swing.JFileChooser;

/**
 *
 * @author tiger
 */
public class BuyCar extends javax.swing.JFrame {

    /**
     * Creates new form BuyCar
     */
    public BuyCar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_FN = new javax.swing.JLabel();
        lbl_Surname = new javax.swing.JLabel();
        lbl_Cell = new javax.swing.JLabel();
        lbl_Gender = new javax.swing.JLabel();
        lbl_Occupation = new javax.swing.JLabel();
        txt_fName = new javax.swing.JTextField();
        txt_Surname = new javax.swing.JTextField();
        txt_tID = new javax.swing.JTextField();
        txt_Occupation = new javax.swing.JTextField();
        cmb_Gender = new javax.swing.JComboBox<>();
        lbl_FN1 = new javax.swing.JLabel();
        txt_Home = new javax.swing.JTextField();
        lbl_Surname1 = new javax.swing.JLabel();
        txt_WorkA = new javax.swing.JTextField();
        lbl_Cell1 = new javax.swing.JLabel();
        txt_GPay = new javax.swing.JTextField();
        lbl_Cell2 = new javax.swing.JLabel();
        txt_NPay = new javax.swing.JTextField();
        lbl_Cell3 = new javax.swing.JLabel();
        rBtn_Yes = new javax.swing.JRadioButton();
        rBtn_No = new javax.swing.JRadioButton();
        lbl_Cell4 = new javax.swing.JLabel();
        cmb_Vehicles = new javax.swing.JComboBox<>();
        lbl_Cell7 = new javax.swing.JLabel();
        txt_Cell = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lbl_FN2 = new javax.swing.JLabel();
        txt_KinCell = new javax.swing.JTextField();
        lbl_Surname2 = new javax.swing.JLabel();
        txt_kinfName = new javax.swing.JTextField();
        lbl_Cell5 = new javax.swing.JLabel();
        txt_KinSurname = new javax.swing.JTextField();
        txt_Relationship = new javax.swing.JTextField();
        lbl_Occupation1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbl_FN3 = new javax.swing.JLabel();
        lbl_Cell6 = new javax.swing.JLabel();
        lbl_Surname3 = new javax.swing.JLabel();
        txt_ID = new javax.swing.JTextField();
        txt_Payslip = new javax.swing.JTextField();
        txt_License = new javax.swing.JTextField();
        btn_ID = new javax.swing.JButton();
        btn_Payslip = new javax.swing.JButton();
        btn_License = new javax.swing.JButton();
        btn_Submit = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Information"));

        lbl_FN.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_FN.setText("First name");

        lbl_Surname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Surname.setText("Surname");

        lbl_Cell.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell.setText("ID No");

        lbl_Gender.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Gender.setText("Gender");

        lbl_Occupation.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Occupation.setText("Occupation");

        cmb_Gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female", "Other" }));

        lbl_FN1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_FN1.setText("Home Address");

        lbl_Surname1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Surname1.setText("Work Address");

        txt_WorkA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_WorkAActionPerformed(evt);
            }
        });

        lbl_Cell1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell1.setText("Gross Pay");

        lbl_Cell2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell2.setText("Net Pay");

        lbl_Cell3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell3.setText("Valid License");

        rBtn_Yes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtn_Yes.setText("Yes");
        rBtn_Yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_YesActionPerformed(evt);
            }
        });

        rBtn_No.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rBtn_No.setText("No");
        rBtn_No.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtn_NoActionPerformed(evt);
            }
        });

        lbl_Cell4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell4.setText("Vehicle");

        cmb_Vehicles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Polo", "Polo Vivo", "T-Cross", "T-Roc" }));

        lbl_Cell7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell7.setText("Cell No");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Occupation)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Cell7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Cell, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Gender)
                            .addGap(36, 36, 36)
                            .addComponent(cmb_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Cell)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_tID, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_Surname)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(lbl_FN)
                            .addGap(18, 18, 18)
                            .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Cell1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_GPay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Surname1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_WorkA, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_FN1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_Home, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_Cell2)
                            .addComponent(lbl_Cell3))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_NPay, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(rBtn_Yes)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rBtn_No)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_Cell4)
                        .addGap(61, 61, 61)
                        .addComponent(cmb_Vehicles, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_FN1)
                            .addComponent(txt_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Surname1)
                            .addComponent(txt_WorkA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cell1)
                            .addComponent(txt_GPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cell2)
                            .addComponent(txt_NPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cell3)
                            .addComponent(rBtn_Yes)
                            .addComponent(rBtn_No))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_Vehicles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Cell4))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_FN)
                            .addComponent(txt_fName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Surname)
                            .addComponent(txt_Surname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cell)
                            .addComponent(txt_tID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Cell7)
                            .addComponent(txt_Cell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Gender)
                            .addComponent(cmb_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_Occupation)
                            .addComponent(txt_Occupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Next of Kin"));

        lbl_FN2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_FN2.setText("First name");

        lbl_Surname2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Surname2.setText("Surname");

        lbl_Cell5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell5.setText("Cell No");

        lbl_Occupation1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Occupation1.setText("Relationship");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_Cell5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_KinCell, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_Surname2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_KinSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_FN2)
                        .addGap(18, 18, 18)
                        .addComponent(txt_kinfName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_Occupation1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_Relationship)))
                .addContainerGap(133, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FN2)
                    .addComponent(txt_kinfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Surname2)
                    .addComponent(txt_KinSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cell5)
                    .addComponent(txt_KinCell, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Occupation1)
                    .addComponent(txt_Relationship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Attachements"));

        lbl_FN3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_FN3.setText("ID");

        lbl_Cell6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Cell6.setText("License");

        lbl_Surname3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbl_Surname3.setText("Latest Payslip");

        txt_Payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PayslipActionPerformed(evt);
            }
        });

        btn_ID.setText("Browse");
        btn_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IDActionPerformed(evt);
            }
        });

        btn_Payslip.setText("Browse");
        btn_Payslip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PayslipActionPerformed(evt);
            }
        });

        btn_License.setText("Browse");
        btn_License.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LicenseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_Surname3)
                    .addComponent(lbl_FN3)
                    .addComponent(lbl_Cell6))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_License, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(txt_ID)
                    .addComponent(txt_Payslip, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_ID)
                    .addComponent(btn_Payslip)
                    .addComponent(btn_License))
                .addGap(23, 23, 23))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_FN3)
                    .addComponent(txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_ID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Surname3)
                    .addComponent(txt_Payslip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Payslip))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_Cell6)
                    .addComponent(txt_License, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_License))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_Submit.setText("Submit Application");
        btn_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SubmitActionPerformed(evt);
            }
        });

        btn_Back.setText("Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_Submit)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Back)
                    .addComponent(btn_Submit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SubmitActionPerformed
        // TODO add your handling code here:
        
        saveData();
    }//GEN-LAST:event_btn_SubmitActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        // TODO add your handling code here:
        HomePage home = new HomePage();
        this.setVisible(false);
        home.setVisible(true);
    }//GEN-LAST:event_btn_BackActionPerformed

    private void rBtn_YesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_YesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtn_YesActionPerformed

    private void rBtn_NoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtn_NoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtn_NoActionPerformed

    private void txt_WorkAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_WorkAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_WorkAActionPerformed

    private void txt_PayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PayslipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PayslipActionPerformed

    private void btn_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IDActionPerformed
 
        // ID BUTTON SAVE location AND DISABLE FROM EDITING TO TXT_ID
        JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.home") + "\\Documents")); //Downloads Directory as default
        chooser.setDialogTitle("Select ID");
        chooser.setAcceptAllFileFilterUsed(true);
        
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        { 
            String fileID = chooser.getSelectedFile().getPath();
            txt_ID.setText(fileID);
            txt_ID.setEditable(false);
        }
        
    }//GEN-LAST:event_btn_IDActionPerformed

    private void btn_PayslipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PayslipActionPerformed

        // Payslip BUTTON SAVE location AND DISABLE FROM EDITING TO TXT_Payslip
        JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.home") + "\\Documents")); //Downloads Directory as default
        chooser.setDialogTitle("Select Payslip");
        chooser.setAcceptAllFileFilterUsed(true);
        
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        { 
            String fileID = chooser.getSelectedFile().getPath();
            txt_Payslip.setText(fileID);
            txt_Payslip.setEditable(false);
        }
    }//GEN-LAST:event_btn_PayslipActionPerformed

    private void btn_LicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LicenseActionPerformed
        // TODO add your handling code here:
        // License BUTTON SAVE location AND DISABLE FROM EDITING TO txt_License
        JFileChooser chooser = new JFileChooser(new File(System.getProperty("user.home") + "\\Documents")); //Downloads Directory as default
        chooser.setDialogTitle("Select License");
        chooser.setAcceptAllFileFilterUsed(true);
        
        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION)
        { 
            String fileID = chooser.getSelectedFile().getPath();
            txt_License.setText(fileID);
            txt_License.setEditable(false);
        }
    }//GEN-LAST:event_btn_LicenseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuyCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuyCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuyCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuyCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuyCar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_ID;
    private javax.swing.JButton btn_License;
    private javax.swing.JButton btn_Payslip;
    private javax.swing.JButton btn_Submit;
    private javax.swing.JComboBox<String> cmb_Gender;
    private javax.swing.JComboBox<String> cmb_Vehicles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl_Cell;
    private javax.swing.JLabel lbl_Cell1;
    private javax.swing.JLabel lbl_Cell2;
    private javax.swing.JLabel lbl_Cell3;
    private javax.swing.JLabel lbl_Cell4;
    private javax.swing.JLabel lbl_Cell5;
    private javax.swing.JLabel lbl_Cell6;
    private javax.swing.JLabel lbl_Cell7;
    private javax.swing.JLabel lbl_FN;
    private javax.swing.JLabel lbl_FN1;
    private javax.swing.JLabel lbl_FN2;
    private javax.swing.JLabel lbl_FN3;
    private javax.swing.JLabel lbl_Gender;
    private javax.swing.JLabel lbl_Occupation;
    private javax.swing.JLabel lbl_Occupation1;
    private javax.swing.JLabel lbl_Surname;
    private javax.swing.JLabel lbl_Surname1;
    private javax.swing.JLabel lbl_Surname2;
    private javax.swing.JLabel lbl_Surname3;
    private javax.swing.JRadioButton rBtn_No;
    private javax.swing.JRadioButton rBtn_Yes;
    private javax.swing.JTextField txt_Cell;
    private javax.swing.JTextField txt_GPay;
    private javax.swing.JTextField txt_Home;
    private javax.swing.JTextField txt_ID;
    private javax.swing.JTextField txt_KinCell;
    private javax.swing.JTextField txt_KinSurname;
    private javax.swing.JTextField txt_License;
    private javax.swing.JTextField txt_NPay;
    private javax.swing.JTextField txt_Occupation;
    private javax.swing.JTextField txt_Payslip;
    private javax.swing.JTextField txt_Relationship;
    private javax.swing.JTextField txt_Surname;
    private javax.swing.JTextField txt_WorkA;
    private javax.swing.JTextField txt_fName;
    private javax.swing.JTextField txt_kinfName;
    private javax.swing.JTextField txt_tID;
    // End of variables declaration//GEN-END:variables

    private void saveData() { 
       String filename = txt_fName.getText() + " " + txt_Surname.getText() + ".txt";
       FileWriter fw;
       
       try {
           fw = new FileWriter(filename);
           
           if(rBtn_Yes.isSelected()){
               fw.write("Personal Information:  \n\n");
               fw.write("----------------------------------------- \n\n");
               fw.write("Full Name: " + txt_fName.getText() + " " + txt_Surname.getText() + "\n\n");
               fw.write("ID Number: " + txt_tID.getText() + "\n\n");
               fw.write("Gender: " + cmb_Gender.getSelectedItem() + "\n\n");
               fw.write("Occupation: " + txt_Occupation.getText() + "\n\n");
               fw.write("Home Address: " + txt_Home.getText() + "\n\n");
               fw.write("Work Address: " + txt_WorkA.getText() + "\n\n");
               fw.write("Gross Pay: " + txt_GPay.getText() + "\n\n");
               fw.write("Net Pay: " + txt_NPay.getText() + "\n\n");
               fw.write("Valid License: " + "Yes" + "\n\n");
               fw.write("Model: " + cmb_Vehicles.getSelectedItem() + "\n\n");
               fw.write("Net Pay: " + txt_NPay.getText() + "\n\n");
           
               fw.write("Next of Kin Information:  \n\n");
               fw.write("----------------------------------------- \n\n");
               fw.write("Full Names: " + txt_kinfName.getText() + " " + txt_KinSurname.getText() +  "\n\n");
               fw.write("Cell Number: " + txt_KinCell.getText() + "\n\n");
               fw.write("Relationship: " + txt_Relationship.getText() + "\n\n");
               fw.close();
               HomePage home = new HomePage();
               this.setVisible(false);
               home.setVisible(true);
           }else {
               HomePage home = new HomePage();
               this.setVisible(false);
               home.setVisible(true);
           }

       } catch (Exception ex) {
           ex.printStackTrace();
       }
 
        
    }
}


